apiVersion: v1
kind: Service
metadata:
  name: owner-service
  namespace: yelp-lab2
spec:
  selector:
    app: owner-service
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner-service
  template:
    metadata:
      labels:
        app: owner-service
    spec:
      containers:
        - name: owner-service
          image: 197496953539.dkr.ecr.us-east-2.amazonaws.com/lab2-owner-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: lab2-config
            - secretRef:
                name: lab2-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
