apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: yelp-lab2
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: lab1-restaurant-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: lab2-config
            - secretRef:
                name: lab2-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
