apiVersion: v1
kind: Service
metadata:
  name: review-worker-service
  namespace: yelp-lab2
spec:
  selector:
    app: review-worker-service
  ports:
    - port: 8005
      targetPort: 8005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker-service
  namespace: yelp-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-worker-service
  template:
    metadata:
      labels:
        app: review-worker-service
    spec:
      containers:
        - name: review-worker-service
          image: lab1-review-worker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: lab2-config
            - secretRef:
                name: lab2-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
