apiVersion: v1
kind: Secret
metadata:
  name: lab2-secrets
  namespace: yelp-lab2
type: Opaque
stringData:
  JWT_SECRET_KEY: change-me-before-aws
  MONGO_INITDB_ROOT_USERNAME: lab2admin
  MONGO_INITDB_ROOT_PASSWORD: lab2secret
  MONGODB_URL: mongodb://lab2admin:lab2secret@mongodb:27017/?authSource=admin
